name: Update Contributors

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch contributors and update README
        run: |
          CONTRIBUTORS=$(curl -s https://api.github.com/repos/GodOfZap/IS/contributors | jq -r '.[] | "- [\(.login)](\(.html_url))"')
          echo "Fetched contributors:"
          echo "$CONTRIBUTORS"

          if [ -n "$CONTRIBUTORS" ]; then
            awk '/<!-- CONTRIBUTORS:START -->/{print;print "";print "__CONTRIBUTORS__";next} /<!-- CONTRIBUTORS:END -->/{print "";print;next} 1' README.md > temp.md
            sed "/__CONTRIBUTORS__/{
              r /dev/stdin
              d
            }" temp.md <<< "$CONTRIBUTORS" > README.md
          else
            echo "No contributors found. Skipping README update."
          fi

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/GodOfZap/IS.git
          git add README.md
          git diff --cached --quiet || git commit -m "Update contributors list"
          git push origin HEAD:main
