name: Update README and Badges

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Call all APIs
        run: |
          echo "Calling all APIs..."
          # Example API calls
          # Replace these with your actual API calls
          curl -s https://api.example.com/first
          curl -s https://api.example.com/second
          # Add more API calls as needed
          echo "All API calls completed."

      - name: Fetch contributors and update README
        run: |
          # Wait 15 seconds before fetching contributors
          echo "Waiting for 15 seconds before fetching contributors..."
          sleep 15

          # Fetch contributors
          echo "Fetching contributors..."
          CONTRIBUTORS=$(curl -s https://api.github.com/repos/GodOfZap/IS/contributors | jq -r '.[] | "<a href=\"\(.html_url)\">\n  <img src=\"\(.avatar_url)\" width=\"60\" height=\"60\" alt=\"\(.login)\" style=\"border-radius: 50%;\" />\n</a>\n"')
          
          echo "Contributors fetched:"
          echo "$CONTRIBUTORS"

          # Optional: wait again after fetching
          # echo "Waiting for 15 seconds after fetching..."
          # sleep 15

          # Update README with contributors
          if [ -n "$CONTRIBUTORS" ]; then
            sed '/<!-- CONTRIBUTORS:START -->/,/<!-- CONTRIBUTORS:END -->/c\
<!-- CONTRIBUTORS:START -->\n'"$CONTRIBUTORS"'\n<!-- CONTRIBUTORS:END -->' README.md > temp.md
            mv temp.md README.md
            echo "README updated with new contributors."
          else
            echo "No contributors found. Skipping README update."
          fi

      - name: Update badges
        run: |
          # Example: Update badge markdown links
          # Replace with your actual badge URLs and update logic
          sed -i 's|!\[build status\](https://img.shields.io/badge/build-passing-brightgreen)|![build status](https://img.shields.io/badge/build-passing-brightgreen)|' README.md
          
          # Add more badge updates as needed
          
          echo "Badges updated."
          
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update README with contributors and badges"
          branch: main
